---
abstract: 'SOCKS enable any POE Component'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.90'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Client-SOCKS
no_index:
  directory:
    - examples
    - inc
    - t
provides:
  POE::Component::Client::SOCKS:
    file: lib/POE/Component/Client/SOCKS.pm
    version: 1.00
requires:
  POE: 1.005
  POE::Filter::Stream: 0
  POE::Wheel::ReadWrite: 0
  POE::Wheel::SocketFactory: 0
  perl: 5.6.0
resources:
  homepage: http://github.com/bingos/poe-component-client-socks/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/poe-component-client-socks.git
version: 1.00
